ci: remove jekyll deploy action
It's failing on ...

> bundle install
/opt/hostedtoolcache/Ruby/3.1.6/x64/bin/bundle config --local path /home/runner/work/rdmolony.github.io/rdmolony.github.io/vendor/bundle
/opt/hostedtoolcache/Ruby/3.1.6/x64/bin/bundle config --local deployment true
Cache key: setup-ruby-bundler-cache-v6-ubuntu-24.04-x64-ruby-3.1.6-wd-/home/runner/work/rdmolony.github.io/rdmolony.github.io-with--without--only--Gemfile.lock-2d05394e6737ebbd77a7f92ff05a54266f62d624697acb53c44da98283ca1d8e
Warning: Failed to restore: Cache service responded with 422
/opt/hostedtoolcache/Ruby/3.1.6/x64/bin/bundle install --jobs 4
Fetching gem metadata from https://rubygems.org/.........
activesupport-8.0.2 requires ruby version >= 3.2.0, which is incompatible with
the current version, 3.1.6
Error: The process '/opt/hostedtoolcache/Ruby/3.1.6/x64/bin/bundle' failed with exit code 5

... which is likely an issue with GitHub